/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export default class CommonConstants {

  /**
   * Month.
   */
  static readonly MONTHS = 12;

  /**
   * January.
   */
  static readonly JANUARY = 1;

  /**
   * A week.
   */
  static readonly WEEK_NUMBER = 7;

  /**
   * Month number.
   */
  static readonly MONTH_NUMBER = 35;

  /**
   * Small grid height.
   */
  static readonly GRID_HEIGHT_L = 360;

  /**
   * Large grid height.
   */
  static readonly GRID_HEIGHT_M = 300;

  /**
   * Outside margin.
   */
  static readonly ELEMENTS_MARGIN = 12;

  /**
   * One hundred percent.
   */
  static readonly ONE_HUNDRED_PERCENT: string = '100%';

  /**
   * One hundred eleven percent.
   */
  static readonly ONE_HUNDRED_ELEVEN_PERCENT: string = '111%';

  /**
   * Ninety two percent.
   */
  static readonly NINETY_PERCENT: string = '90%';

  /**
   * Ninety two percent.
   */
  static readonly NINETY_TWO_PERCENT: string = '92%';

  /**
   * Ninety five percent.
   */
  static readonly NINETY_FIVE_PERCENT: string = '95%';

  /**
   * Eighty five percent.
   */
  static readonly EIGHTY_FIVE_PERCENT: string = '85%';

  /**
   * Thirty percent.
   */
  static readonly THIRTY_PERCENT: string = '30%';

  /**
   * Forty percent.
   */
  static readonly FORTY_PERCENT: string = '40%';

  /**
   * Seventy-five percent.
   */
  static readonly SEVENTY_FIVE_PERCENT: string = '75%';

  /**
   * Rotation angle.
   */
  static readonly ANGLE: number = 45;

  /**
   * Line Spacing.
   */
  static readonly SPACE: number = 15;

  /**
   * Moving distance.
   */
  static readonly TRANSLATE: number = 1000;

  /**
   * Zero six.
   */
  static readonly ZERO_SIX: number = 0.6;

  /**
   * Zero eight.
   */
  static readonly ZERO_EIGHT: number = 0.8;

  /**
   * Duration.
   */
  static readonly DURATION: number = 1200;

  /**
   * Delay.
   */
  static readonly DELAY: number = 500;

  /**
   * GridCount.
   */
  static readonly GRID_COUNT: number = 2;

  /**
   * Zero.
   */
  static readonly ZERO: number = 0;

  /**
   * Four
   */
  static readonly FOUR: number = 4;

  /**
   * Eight.
   */
  static readonly EIGHT: number = 8;

  /**
   * Twelves.
   */
  static readonly TWELVES: number = 12;

  /**
   * Space.
   */
  static readonly SPACE_ONE: number = 20;

  /**
   * Element margin large.
   */
  static readonly ELEMENTS_MARGIN_L: number = 24;

  /**
   * Element margin small.
   */
  static readonly ELEMENTS_MARGIN_M: number = 8;

  /**
   * 0.0.
   */
  static readonly ZERO_ZERO: number = 0.0;

  /**
   * 0.3.
   */
  static readonly ZERO_Three: number = 0.3;

  /**
   * 1.0.
   */
  static readonly ONE_ZERO: number = 1.0;

  /**
   * Saturday.
   */
  static readonly SATURDAY: string = '六';

  /**
   * Sunday.
   */
  static readonly SUNDAY: string = '日';

  /**
   * Seven grid.
   */
  static readonly GRID_SEVEN: string = '1fr 1fr 1fr 1fr 1fr 1fr 1fr';

  /**
   * Six grid.
   */
  static readonly GRID_SIX: string = '1fr 1fr 1fr 1fr 1fr 1fr';

  /**
   * Five grid.
   */
  static readonly GRID_FIVE: string = '1fr 1fr 1fr 1fr 1fr';

  /**
   * The entry ability tag.
   */
  static readonly TAG_ABILITY: string = 'EntryAbility';

  /**
   * The home page tag.
   */
  static readonly TAG_HOME: string = 'HomePage';

  /**
   * The Common utils tag.
   */
  static readonly TAG_COMMON_UTILS: string = 'CommonUtils';

  /**
   * Custom dialog widget tag.
   */
  static readonly TAG_CUSTOM: string = 'CustomDialogWidget';

  /**
   * Width the percentage of the 100.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Height the percentage of the 100.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Date year
   */
  static readonly DATE_YEAR: string = '年';

  /**
   * Date month
   */
  static readonly DATE_MONTH: string = '月';

  /**
   * Date day
   */
  static readonly DATE_DAY: string = '日';

  /**
   * Date dialog start time.
   */
  static readonly START_TIME: string = '1900-1-1';

  /**
   * Date dialog select time.
   */
  static readonly SELECT_TIME: string = '1990-1-1';

  /**
   * Image back margin left of the 7.2.
   */
  static readonly BACK_MARGIN_LEFT: string = '7.2%';

  /**
   * Image avatar margin top of the 5.5.
   */
  static readonly AVATAR_MARGIN_TOP: string = '5.5%';

  /**
   * Text personal margin top of the 2.1.
   */
  static readonly PERSONAL_MARGIN_TOP: string = '2.1%';

  /**
   * Common dialog width of the 93.3.
   */
  static readonly COMMON_DIALOG_WIDTH: string = '93.3%';

  /**
   * Join comma
   */
  static readonly COMMA: string = '，';

  /**
   * Image back margin top of the 19.
   */
  static readonly BACK_MARGIN_TOP: number = 19;

  /**
   * Font weight of the 500.
   */
  static readonly BIGGER: number = 500;

  /**
   * Dialog y-axis offset distance of the 20.
   */
  static readonly DY_OFFSET: number = -20;

  /**
   * Current month plus one.
   */
  static readonly PLUS_ONE: number = 1;

  /**
   * Layout weight size of the 1.
   */
  static readonly WEIGHT_ONE: number = 1;

  /**
   * Text common max lines of the 1.
   */
  static readonly ONE_LINES: number = 1;
}